"""Exact d=67 Ford data; no floating-point predicates or Euclidean division.

The cover is generated by dyadic subdivision and independently checked by
verify_geometry.py. The construction uses finite candidate rows; it does not
claim that every candidate defines a two-dimensional face.
"""
from fractions import Fraction as F
from math import gcd
from itertools import product
ZERO = (0, 0)
ONE = (1, 0)
TAU = (0, 1)


def add(x, y): return x[0]+y[0], x[1]+y[1]
def neg(x): return -x[0], -x[1]
def sub(x, y): return add(x, neg(y))
def mul(x, y):
    a,b=x;c,d=y
    return a*c-17*b*d, a*d+b*c+b*d

def conj(x): return x[0]+x[1], -x[1]
def norm(x): return mul(x,conj(x))[0]
def det(x,y): return x[0]*y[1]-x[1]*y[0]

def primitive(c,l):
    v=[c,mul(c,TAU),l,mul(l,TAU)]
    return gcd(*(abs(det(v[i],v[j])) for i in range(4) for j in range(i))) == 1

def quotient(numerator, denominator):
    n=norm(denominator)
    p=mul(numerator,conj(denominator))
    if p[0]%n or p[1]%n: return None
    return p[0]//n,p[1]//n

def center(c,l):
    p=mul(l,conj(c));n=norm(c)
    return F(p[0],n),F(p[1],n)

def q(c,l,a,b):
    u,v=center(c,l);x,y=a-u,b-v
    return F(1,norm(c))-x*x-x*y-17*y*y

def candidates(limit=29):
    # The c and lambda bounds follow from N(c)<=29 and N(lambda)<169.
    cs=[(a,b) for a,b in product(range(-6,7),range(-1,2))
        if 0<norm((a,b))<=limit]
    ls=[(a,b) for a,b in product(range(-14,15),range(-3,4))
        if norm((a,b))<169]
    # Negating both gives the same PSL hemisphere; use one sign.
    return [(c,l) for c in cs if c>(0,0) for l in ls if primitive(c,l)]

def find_matrix(c,l):
    # Row (c,-l), determinant ad-bc=1. Search representatives a;
    # divisibility is exact and PID ensures eventual termination.
    d=neg(l)
    for n in range(200):
        for a in product(range(-n,n+1),repeat=2):
            if norm(a)>n: continue
            b=quotient(sub(mul(a,d),ONE),c)
            if b is not None:
                if sub(mul(a,d),mul(b,c))!=ONE: raise ArithmeticError('determinant')
                return (a,b,c,d)
    raise ArithmeticError('Bezout search cap; do not certify')

