"""Evaluate any registered group through the same report/certificate interface."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from core.assemble import evaluate
from core.certificate import certificate_payload, report_payload
from groups import GroupKey, LevelIdeal
from fields.quadratic import get_field


def main(default_field=None):
    parser = argparse.ArgumentParser(description=__doc__)
    if default_field is None:
        parser.add_argument("field", help="i, omega, or a supported d")
    else:
        parser.add_argument("field", nargs="?", default=str(default_field))
    parser.add_argument("--subgroup", choices=("full", "gamma0", "gamma1", "principal"), default="full")
    parser.add_argument("--level-generator", type=int, nargs=2, metavar=("A", "B"), default=(1, 0),
                        help="principal ideal generated by A+B*g in the standard integral basis")
    parser.add_argument("--mechanical", action="store_true")
    parser.add_argument("--k", type=int, default=2)
    parser.add_argument("--R", type=float, default=40)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    kind = int(args.field) if args.field.isdigit() else args.field
    try:
        F = get_field(kind)
        ideal = LevelIdeal.principal(F.d, tuple(args.level_generator))
        key = GroupKey.congruence(args.subgroup, ideal)
        E = evaluate(key, k=args.k, R=args.R, verbose=False, include_elliptic=not args.mechanical)
        payload = report_payload(E) if args.mechanical else certificate_payload(E)
    except (ValueError, ArithmeticError) as exc:
        parser.error(str(exc))
    text = json.dumps(payload, indent=2)+"\n"
    if args.output:
        args.output.write_text(text)
        kind = "mechanical report" if args.mechanical else "spectral certificate"
        print(f"Wrote {args.output}; {kind}; B = {E.bound}.")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
