"""Finite generated images and their regular actions, independent of analysis."""
from collections import Counter, deque
from dataclasses import dataclass
from fractions import Fraction
from groups.identity import LevelIdeal
from quotients.arithmetic import ResidueRing, ProjectiveMatrices


def standard_generators():
    """S, T_1, T_g in the standard integral basis (same lifts in every field)."""
    return (((0, 0), (-1, 0), (1, 0), (0, 0)),
            ((1, 0), (1, 0), (0, 0), (1, 0)),
            ((1, 0), (0, 1), (0, 0), (1, 0)))


@dataclass(frozen=True)
class FiniteAction:
    ideal: LevelIdeal
    vertices: tuple
    generators: tuple
    permutations: tuple

    @property
    def order(self):
        return len(self.vertices)

    @property
    def degree(self):
        return len(self.generators)

    @property
    def symmetric(self):
        return Counter(self.generators) == Counter(
            ProjectiveMatrices(ResidueRing(self.ideal)).inverse(g) for g in self.generators)

    def adjacency_product(self, vector):
        if len(vector) != self.order:
            raise ValueError("vector length must match the quotient order")
        return tuple(sum(vector[p[i]] for p in self.permutations) for i in range(self.order))

    def transition_product(self, vector):
        return tuple(x*Fraction(1, self.degree) for x in self.adjacency_product(vector))

    def payload(self):
        return dict(d=self.ideal.field_d, level=self.ideal.payload(), order=self.order,
                    degree=self.degree, symmetric=self.symmetric,
                    vertices=self.vertices, generators=self.generators, permutations=self.permutations,
                    convention="right regular action; global +/-; generator multiset retains loops and repetitions",
                    completeness="entire subgroup generated by the listed reduced matrices",
                    spectral_claim=False)


def generated_action(ideal, generators=None, *, symmetric=True, max_vertices=10000):
    """Enumerate the complete generated subgroup or raise at the size cap.

    This makes no surjectivity assertion about a full ambient finite group.
    Symmetrization appends one inverse per input, preserving multiplicities.
    """
    if not isinstance(max_vertices, int) or isinstance(max_vertices, bool) or max_vertices < 1:
        raise ValueError("max_vertices must be a positive integer")
    matrices = ProjectiveMatrices(ResidueRing(ideal))
    lifts = standard_generators() if generators is None else tuple(generators)
    images = tuple(matrices.reduce(g) for g in lifts)
    if not images:
        raise ValueError("at least one generator is required")
    if symmetric:
        images += tuple(matrices.inverse(g) for g in images)
    vertices, indices = [matrices.identity], {matrices.identity: 0}
    queue = deque(vertices)
    while queue:
        v = queue.popleft()
        for g in images:
            w = matrices.mul(v, g)
            if w not in indices:
                if len(vertices) >= max_vertices:
                    raise ValueError("quotient size cap reached; no incomplete action is returned")
                indices[w] = len(vertices)
                vertices.append(w)
                queue.append(w)
    permutations = tuple(tuple(indices[matrices.mul(v, g)] for v in vertices) for g in images)
    return FiniteAction(ideal, tuple(vertices), images, permutations)
