"""Exact d=43 Ford data; no floating-point predicates or Euclidean division.

The cover is generated by dyadic subdivision and independently checked by
verify_geometry.py. The construction uses finite candidate rows; it does not
claim that every candidate defines a two-dimensional face.
"""
from fractions import Fraction as F
from math import gcd
from itertools import product
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ZERO = (0, 0)
ONE = (1, 0)
TAU = (0, 1)


def add(x, y): return x[0]+y[0], x[1]+y[1]
def neg(x): return -x[0], -x[1]
def sub(x, y): return add(x, neg(y))
def mul(x, y):
    a,b=x;c,d=y
    return a*c-11*b*d, a*d+b*c+b*d

def conj(x): return x[0]+x[1], -x[1]
def norm(x): return mul(x,conj(x))[0]
def det(x,y): return x[0]*y[1]-x[1]*y[0]

def primitive(c,l):
    v=[c,mul(c,TAU),l,mul(l,TAU)]
    return gcd(*(abs(det(v[i],v[j])) for i in range(4) for j in range(i))) == 1

def quotient(numerator, denominator):
    n=norm(denominator)
    p=mul(numerator,conj(denominator))
    if p[0]%n or p[1]%n: return None
    return p[0]//n,p[1]//n

def center(c,l):
    p=mul(l,conj(c));n=norm(c)
    return F(p[0],n),F(p[1],n)

def q(c,l,a,b):
    u,v=center(c,l);x,y=a-u,b-v
    return F(1,norm(c))-x*x-x*y-11*y*y

def candidates(limit=23):
    # The c and lambda bounds follow from N(c)<=23 and N(lambda)<100.
    cs=[(a,b) for a,b in product(range(-5,6),range(-2,3))
        if 0<norm((a,b))<=limit]
    ls=[(a,b) for a,b in product(range(-11,12),range(-4,5))
        if norm((a,b))<100]
    # Negating both gives the same PSL hemisphere; use one sign.
    return [(c,l) for c in cs if c>(0,0) for l in ls if primitive(c,l)]

def find_matrix(c,l):
    # Row (c,-l), determinant ad-bc=1. Search representatives a;
    # divisibility is exact and PID ensures eventual termination.
    d=neg(l)
    for n in range(200):
        for a in product(range(-n,n+1),repeat=2):
            if norm(a)>n: continue
            b=quotient(sub(mul(a,d),ONE),c)
            if b is not None:
                if sub(mul(a,d),mul(b,c))!=ONE: raise ArithmeticError('determinant')
                return (a,b,c,d)
    raise ArithmeticError('Bezout search cap; do not certify')

def cover_spheres():
    cs=[(a,b) for a,b in product(range(-4,5),range(-1,2))
        if 0<norm((a,b))<=11]
    ls=list(product(range(-10,11),range(-4,5)))
    out={}
    for c in cs:
        for l in ls:
            u,v=center(c,l)
            if -2<=u<=2 and -1<=v<=1 and primitive(c,l):
                out.setdefault((u,v,norm(c)),(c,l))
    return list(out.values())

def generate_cover():
    spheres=cover_spheres();leaves=[]
    def visit(a,b,w,depth):
        corners=((a,b),(a+w,b),(a,b+w),(a+w,b+w))
        best=F(-100);chosen=None
        for c,l in spheres:
            mn=min(q(c,l,x,y) for x,y in corners)
            if mn>best:best,chosen=mn,(c,l)
        if best>=F(1,24):
            c,l=chosen
            leaves.append(dict(a=str(a),b=str(b),w=str(w),c=c,l=l))
            return
        if depth>=12: raise ArithmeticError(f'cover depth exceeded at {a},{b}')
        h=w/2
        for da,db in ((0,0),(1,0),(0,1),(1,1)):
            visit(a+da*h,b+db*h,h,depth+1)
    visit(F(-1,2),F(-1,2),F(1),0)
    return leaves

if __name__=='__main__':
    leaves=generate_cover()
    (ROOT/'cover_witnesses.json').write_text(json.dumps(leaves,indent=2)+'\n')
    print('cover leaves',len(leaves),'candidate rows',len(candidates()))
